"""empty message

Revision ID: 8e25899f2251
Revises: b26de28ce928
Create Date: 2022-12-15 21:42:31.527097

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e25899f2251'
down_revision = 'b26de28ce928'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=False))
        batch_op.drop_column('context')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('context', mysql.TEXT(), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
